version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: 'cross_browser_cookie'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '123456'
    logging:
      driver: none
    volumes:
      - ./packages/backend/db/migrations:/docker-entrypoint-initdb.d

  backend:
    image: node:14-alpine
    working_dir: /app/backend
    volumes:
      - ./packages/backend/src:/app/backend/src
      - ./packages/backend/package.json:/app/backend/package.json
      - ./packages/backend/yarn.lock:/app/backend/yarn.lock
      - ./packages/backend/tsconfig.json:/app/backend/tsconfig.json
    entrypoint: sh -c "yarn && yarn start"
    env_file:
      - ./.env.docker
    ports:
      - 3000:3000
    depends_on:
      - db
